# Generated by Django 5.2.14 on 2026-05-22 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 6, 6)),
        ),
    ]
