# Generated by Django 5.2.14 on 2026-05-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
    ]
