# Generated by Django 5.2.14 on 2026-05-24 14:38

import loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=loans.models.default_due_date),
        ),
    ]
